Getting Started with Pandas

In [8]:
import pandas as pd

df = pd.read_csv("data//movies.csv")

df.columns


Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [20]:
(df[df.vote_average==0.0])

index   budget                  genres                       homepage  \
1464   1464        0             Drama Crime                            NaN   
3669   3669        0            Comedy Drama  http://www.romeothemovie.com/   
3670   3670        0                  Family                            NaN   
3852   3852        0                   Drama                            NaN   
3855   3855  3500000             Documentary    http://www.timetochoose.com   
...     ...      ...                     ...                            ...   
4769   4769        0          Action Western                            NaN   
4771   4771        0                  Horror                            NaN   
4780   4780        0    Thriller Crime Drama                            NaN   
4785   4785        0                   Drama                            NaN   
4794   4794        0  Thriller Horror Comedy                            NaN   

          id                    keywords original_language  \
1464  310706                         NaN                en   
3669  113406                         NaN                en   
3670  447027                         NaN                en   
3852  395766                  miniseries                en   
3855  370662  climate change documentary                en   
...      ...                         ...               ...   
4769   69382                         NaN                en   
4771  220490                         NaN                en   
4780  366967                         NaN                en   
4785  287625                         NaN                en   
4794  286939                         NaN                en   

                         original_title  \
1464                Black Water Transit   
3669               Should've Been Romeo   
3670                    Running Forever   
3852                         The Secret   
3855                     Time to Choose   
...                                 ...   
4769            The Legend of God's Gun   
4771  Her Cry: La Llorona Investigation   
4780                        Dutch Kills   
4785               Stories of Our Lives   
4794       Sanctuary: Quite a Conundrum   

                                               overview  popularity  ...  \
1464  In this action thriller set in post-Katrina Ne...    0.126738  ...   
3669  A self-centered, middle-aged pitchman for a po...    0.407030  ...   
3670  After being estranged since her mother's death...    0.028756  ...   
3852  The Secret is the story of a real-life double ...    0.042346  ...   
3855  Academy Award® winning director Charles Fergus...    1.618138  ...   
...                                                 ...         ...  ...   
4769  A gun-slinging preacher returns to the debauch...    0.003582  ...   
4771  Crew of "Paranormal Legends" went to film thei...    0.056459  ...   
4780  A desperate ex-con is forced to gather his old...    0.038143  ...   
4785  Created by the members of a Nairobi-based arts...    0.327794  ...   
4794  It should have been just a normal day of sex, ...    0.166513  ...   

     runtime                                   spoken_languages    status  \
1464   100.0           [{"iso_639_1": "en", "name": "English"}]  Released   
3669     0.0           [{"iso_639_1": "en", "name": "English"}]  Released   
3670    88.0                                                 []  Released   
3852   200.0                                                 []  Released   
3855   100.0           [{"iso_639_1": "en", "name": "English"}]  Released   
...      ...                                                ...       ...   
4769    78.0                                                 []  Released   
4771    89.0                                                 []  Released   
4780    90.0                                                 []  Released   
4785    60.0  [{"iso_639_1": "sw", "name": "Kiswahili"}, {"i...  Released   
4794    82.0           [{"iso_639_1

In [32]:
(df.spoken_languages.value_counts())


spoken_languages
[{"iso_639_1": "en", "name": "English"}]                                                                                                                                                                                                                                                                                                                                           3171
[{"iso_639_1": "en", "name": "English"}, {"iso_639_1": "es", "name": "Espa\u00f1ol"}]                                                                                                                                                                                                                                                                                               127
[{"iso_639_1": "en", "name": "English"}, {"iso_639_1": "fr", "name": "Fran\u00e7ais"}]                                                                                                                                                 

In [38]:
df_new = df[["title","director","popularity"]]
df_new

title           director  popularity
0                                       Avatar      James Cameron  150.437577
1     Pirates of the Caribbean: At World's End     Gore Verbinski  139.082615
2                                      Spectre         Sam Mendes  107.376788
3                        The Dark Knight Rises  Christopher Nolan  112.312950
4                                  John Carter     Andrew Stanton   43.926995
...                                        ...                ...         ...
4798                               El Mariachi   Robert Rodriguez   14.269792
4799                                 Newlyweds       Edward Burns    0.642552
4800                 Signed, Sealed, Delivered        Scott Smith    1.444476
4801                          Shanghai Calling        Daniel Hsia    0.857008
4802                         My Date with Drew   Brian Herzlinger    1.929883

[4803 rows x 3 columns]

In [40]:
df_new["pop"] = df_new["popularity"].apply(lambda x: x*100)
df_new.head()

C:\Users\palik\AppData\Local\Temp\ipykernel_5660\4124795993.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["pop"] = df_new["popularity"].apply(lambda x: x*100)


title           director  popularity  \
0                                    Avatar      James Cameron  150.437577   
1  Pirates of the Caribbean: At World's End     Gore Verbinski  139.082615   
2                                   Spectre         Sam Mendes  107.376788   
3                     The Dark Knight Rises  Christopher Nolan  112.312950   
4                               John Carter     Andrew Stanton   43.926995   

          pop  
0  15043.7577  
1  13908.2615  
2  10737.6788  
3  11231.2950  
4   4392.6995

In [43]:
df_new.index

RangeIndex(start=0, stop=4803, step=1)

In [52]:
df_new.loc[100]

title         The Curious Case of Benjamin Button
director                            David Fincher
popularity                              60.269279
pop                                     6026.9279
Name: 100, dtype: object

In [58]:
df_new.set_index("title",inplace=True)

KeyError: "None of ['title'] are in the columns"

In [60]:
df_new.index

Index(['Avatar', 'Pirates of the Caribbean: At World's End', 'Spectre',
       'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled',
       'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince',
       'Batman v Superman: Dawn of Justice',
       ...
       'On The Downlow', 'Sanctuary: Quite a Conundrum', 'Bang', 'Primer',
       'Cavite', 'El Mariachi', 'Newlyweds', 'Signed, Sealed, Delivered',
       'Shanghai Calling', 'My Date with Drew'],
      dtype='object', name='title', length=4803)

In [65]:
df_new.loc['Bang']

director      Ash Baron-Cohen
popularity           0.918116
pop                   91.8116
Name: Bang, dtype: object

In [67]:
df_new.reset_index(inplace=True)

In [70]:
df_new.index

RangeIndex(start=0, stop=4803, step=1)

In [72]:
df = pd.read_csv("data//movies.csv")
df.head(4)

title   industry  release_year  \
0                              Pather Panchali  Bollywood          1955   
1  Doctor Strange in the Multiverse of Madness  Hollywood          2022   
2                        Thor: The Dark World   Hollywood          2013   
3                              Thor: Ragnarok   Hollywood          2017   

   imdb_rating                     studio   budget   revenue       unit  \
0          8.3  Government of West Bengal  70000.0  100000.0  Thousands   
1          7.0             Marvel Studios    200.0     954.8   Millions   
2          6.8             Marvel Studios    165.0     644.8   Millions   
3          7.9             Marvel Studios    180.0     854.0   Millions   

  currency language  
0      INR  Bengali  
1      USD  English  
2      USD  English  
3      USD  English

In [1]:
import numpy as np

In [3]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[: 2: 2]

array([1])

In [29]:
arr.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [51]:
np.random.randint(1)

0

In [52]:
arr.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])